name: build/pub release
on:
  push:
    branches: main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.15"
      - name: Install
        run: cd client && npm ci
      - name: Run audit
        run: cd client && npm run test:audit
      - name: Run format test
        run: cd client && npm run test:format
      - name: Run lint test
        run: cd client && npm run test:lint
      - name: Run types test
        run: cd client && npm run test:types
      - name: Run license test
        run: cd client && npm run test:license
      - name: Build the docker-compose stack
        run: docker-compose up -d
      - name: Check running containers
        run: docker ps
      - name: Cypress run tests
        run: make test-e2e-exec

  build-and-publish:
    needs: test
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker tag
        id: tag
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          echo ::set-output name=image_tag::${IMAGE_TAG}
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build
        run: export DOCKER_IMAGE=uscictdocker/opentutor-web-client:${{ steps.tag.outputs.image_tag }} && make docker-build
      - name: Docker tag
        if: startsWith(github.ref, 'refs/tags/')
        run: docker tag "uscictdocker/opentutor-web-client:${{ steps.tag.outputs.image_tag }}" "uscictdocker/opentutor-web-client:${GITHUB_REF#refs/tags/}"
      - name: Docker push
        run: docker push uscictdocker/opentutor-web-client
