name: Publish docker image
on:
  push:
    branches: main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Reject forked repositories
        if: github.repository != 'ICTLearningSciences/opentutor-web-client'
        run: exit 1
      - uses: actions/checkout@v2
      - name: Install
        run: cd client && npm ci
      - name: Run audit
        run: cd client && npm run test:audit
      - name: Run format test
        run: cd client && npm run test:format
      - name: Run lint test
        run: cd client && npm run test:lint
      - name: Run types test
        run: cd client && npm run test:types
      - name: Run license test
        run: cd client && npm run test:license
      - name: Run cypress test
        uses: cypress-io/github-action@v2
        with:
          working-directory: client
          env: CYPRESS_SNAPSHOT_DIFF_DIR=cypress/snapshot/snapshot_failed_diffs
          start: npm run develop  

  build-and-publish:
    needs: test
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Reject forked repositories
        if: github.repository != 'ICTLearningSciences/opentutor-web-client'
        run: exit 1
      - uses: actions/checkout@v2

      - name: Docker tag
        id: tag
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          echo ::set-output name=image_tag::${IMAGE_TAG}

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: cd node && DOCKER_BUILDKIT=1 docker build -t uscictdocker/opentutor-web-client:${{ steps.tag.outputs.image_tag }} .

      - name: Docker push
        run: docker push uscictdocker/opentutor-web-client
