name: test commit
on: [pull_request]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.15"
      - name: Install
        run: cd client && npm ci
      - name: Run audit
        run: cd client && npm run test:audit
      - name: Run format test
        run: cd client && npm run test:format
      - name: Run lint test
        run: cd client && npm run test:lint
      - name: Run types test
        run: cd client && npm run test:types
      - name: Run license test
        run: cd client && npm run test:license

  cypress:
    name: Run cypress tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up -d
      - name: Check running containers
        run: docker ps
      - name: Cypress run tests
        run: make test-e2e-exec
      - name: If Cypress failed, retrieve image diffs
        run: make test-e2e-image-snapshots-copy && mkdir -p cypress/cypress/snapshots/snapshot_failed_diffs
        if: ${{ failure() }}
      - name: If Cypress failed, upload image-diff artifacts
        uses: actions/upload-artifact@v1
        if: ${{ failure() }}
        with:
          name: snapshot_failed_diffs
          path: cypress/cypress/snapshots
